/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class CRFIDVirus_AuthListener */

#ifndef _Included_CRFIDVirus_AuthListener
#define _Included_CRFIDVirus_AuthListener
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
