/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class CRFIDVirus */

#ifndef _Included_CRFIDVirus
#define _Included_CRFIDVirus
#ifdef __cplusplus
extern "C" {
#endif
#undef CRFIDVirus_password
#define CRFIDVirus_password 51966L
/*
 * Class:     CRFIDVirus
 * Method:    AES_decrypt
 * Signature: ([B[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_CRFIDVirus_AES_1decrypt
  (JNIEnv *, jclass, jbyteArray, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
