/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class CRFIDVirus_CRFIDVirusReportListener */

#ifndef _Included_CRFIDVirus_CRFIDVirusReportListener
#define _Included_CRFIDVirus_CRFIDVirusReportListener
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
