/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class CRFIDVirus_AccessListener */

#ifndef _Included_CRFIDVirus_AccessListener
#define _Included_CRFIDVirus_AccessListener
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
