/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class CRFIDVirus_PromiseRN */

#ifndef _Included_CRFIDVirus_PromiseRN
#define _Included_CRFIDVirus_PromiseRN
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
